# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               OpenNFT
tagline:             'Open Neurofeedback Training toolbox'
description:         'OpenNFT is an open source toolbox for fMRI-based neurofeedback training.'
url:                 http://opennft.org
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yury Kush
  url:               http://opennft.org
  email:

# Custom vars
version:             1.0.0
